<a href="https://colab.research.google.com/github/thecont1/class-sharing/blob/main/Oct24_Numpy_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
2+3

In [1]:
import numpy as np

In [ ]:
a = np.arange(4)
a

In [ ]:
b = a.reshape(2, 2)
b

In [ ]:
np.shares_memory(a, b)

In [ ]:
a[0] = 100
a

In [ ]:
b

In [ ]:
a = np.arange(4)
a

In [ ]:
c = a + 2
c

In [ ]:
a

In [ ]:
c

In [ ]:
a[0] = 50
a

In [ ]:
c

In [ ]:
np.shares_memory(a, c)  # Check if a & c have same memory

In [ ]:
print(2 + 3)

In [ ]:
a= np.arange(10)
a

In [ ]:
b = a[::2]
b

In [ ]:
np.shares_memory(a,b)
# Shallow copy

In [ ]:
a = np.arange(4)
a

In [ ]:
c = a[a % 1 == 0]
c

In [ ]:
a[0] = 20

In [ ]:
a

In [ ]:
c

In [ ]:
np.shares_memory(a,c) # Deep Copy

In [ ]:
d = c

In [ ]:
np.shares_memory(d, c)

In [ ]:
a

In [ ]:
a_shallow_copy = a.view() # Function to create shallow copy
a_shallow_copy

In [ ]:
np.shares_memory(a, a_shallow_copy)

In [ ]:
a_deep_copy = a.copy()  # Function to create deep copy
a_deep_copy

In [ ]:
np.shares_memory(a, a_deep_copy)

In [ ]:
t = 10

In [ ]:
r = t.view()

In [2]:
a = np.array([0,1,2,3,4,5])
b = a[a%1 == 0]   # Deep Copy
b[0] = 10
a[:2]   # Slicing -> start to (end-1)

array([0, 1])

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
view_arr = arr.view()   # Shallow Copy -> Same memory -> Any change in one will be reflected in another.
view_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
view_arr[4] = 420
view_arr

array([  0,   1,   2,   3, 420,   5,   6,   7,   8,   9])

In [6]:
arr

array([  0,   1,   2,   3, 420,   5,   6,   7,   8,   9])

In [7]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
copy_arr = arr.copy()   # Deep Copy -> New memory location for copy therefore change in one will not reflect in another.
copy_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
copy_arr[3] = 45
copy_arr

array([ 0,  1,  2, 45,  4,  5,  6,  7,  8,  9])

In [12]:
view_arr

array([  0,   1,   2,   3, 420,   5,   6,   7,   8,   9])

In [13]:
a

array([0, 1, 2, 3, 4, 5])

In [14]:
q = a

In [15]:
np.shares_memory(a, q)

True

In [16]:
arr = np.array([1, 'm', [1,2,3]], dtype = 'object')
arr

array([1, 'm', list([1, 2, 3])], dtype=object)

In [17]:
copy_arr = arr.copy()   # Exception of .copy() i.e. creates shallow copy
copy_arr

array([1, 'm', list([1, 2, 3])], dtype=object)

In [20]:
arr[2][0] = 15
arr

array([1, 'm', list([15, 2, 3])], dtype=object)

In [21]:
copy_arr

array([1, 'm', list([15, 2, 3])], dtype=object)

In [ ]:
copy_arr[0] = 20
copy_arr

In [ ]:
arr

In [ ]:
import copy
copy_arr_2 = copy.deepcopy(arr)   # Deepcopy
copy_arr_2

In [ ]:
arr[0] = 50
arr

In [ ]:
copy_arr_2

In [ ]:
x = np.array([1, 'm', [1,2,3]], dtype = 'object')
x

In [ ]:
y = x.copy()
y

In [ ]:
x[0] = 200
x

In [ ]:
y