In [1]:
import numpy as np

In [2]:
# Create 2D array with random integer elements
arr = np.random.randint(100, size=32).reshape(8, 4)
arr

array([[26, 68, 33, 86],
       [54, 20, 76,  0],
       [46, 40,  0,  0],
       [10, 13, 89, 46],
       [56, 87, 40, 97],
       [60, 43, 56, 81],
       [57, 14, 12, 82],
       [75, 41, 88,  9]])

In [3]:
np.sort(arr)

array([[26, 33, 68, 86],
       [ 0, 20, 54, 76],
       [ 0,  0, 40, 46],
       [10, 13, 46, 89],
       [40, 56, 87, 97],
       [43, 56, 60, 81],
       [12, 14, 57, 82],
       [ 9, 41, 75, 88]])

In [4]:
np.sort(arr)[:, ::-1]

array([[86, 68, 33, 26],
       [76, 54, 20,  0],
       [46, 40,  0,  0],
       [89, 46, 13, 10],
       [97, 87, 56, 40],
       [81, 60, 56, 43],
       [82, 57, 14, 12],
       [88, 75, 41,  9]])

In [5]:
somearr = np.array([1, 2, 3, 4, 5])

h = np.tile(somearr, (2, 2))
h

array([[1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]])

In [6]:
np.shares_memory(somearr, somearr+1)

False

In [7]:
a = np.arange(1, 11)

b = a[a%1 == 0]


In [8]:
np.shares_memory(a, a.view())

True

In [9]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
a.view()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.shares_memory(a, a.copy())

False

In [12]:
import copy
np.shares_memory(a.copy(), copy.deepcopy(a))

False

In [13]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr0 = a.view()

In [15]:
arr1 = a.copy()

In [16]:
arr2 = copy.deepcopy(a)

In [17]:
np.shares_memory(a, arr0)

True

In [18]:
arr = np.random.randint(100, size=32)
arr

array([92, 54, 74, 32, 79, 39, 91, 86, 88, 70, 55, 64, 36, 62, 18, 52, 40,
       13, 57, 69, 76, 39,  1, 37,  5, 70, 61, 59, 83, 30, 34, 79])

In [19]:
np.split(arr, [8, 4, -1])

[array([92, 54, 74, 32, 79, 39, 91, 86]),
 array([], dtype=int64),
 array([79, 39, 91, 86, 88, 70, 55, 64, 36, 62, 18, 52, 40, 13, 57, 69, 76,
        39,  1, 37,  5, 70, 61, 59, 83, 30, 34]),
 array([79])]

In [20]:
np.split(arr, [8, 4, -1])[2]

array([79, 39, 91, 86, 88, 70, 55, 64, 36, 62, 18, 52, 40, 13, 57, 69, 76,
       39,  1, 37,  5, 70, 61, 59, 83, 30, 34])

In [21]:
arr.reshape(4, 8)

array([[92, 54, 74, 32, 79, 39, 91, 86],
       [88, 70, 55, 64, 36, 62, 18, 52],
       [40, 13, 57, 69, 76, 39,  1, 37],
       [ 5, 70, 61, 59, 83, 30, 34, 79]])

In [24]:
np.vsplit(arr.reshape(8, 4), 4)

[array([[92, 54, 74, 32],
        [79, 39, 91, 86]]),
 array([[88, 70, 55, 64],
        [36, 62, 18, 52]]),
 array([[40, 13, 57, 69],
        [76, 39,  1, 37]]),
 array([[ 5, 70, 61, 59],
        [83, 30, 34, 79]])]

In [25]:
np.hsplit(arr.reshape(4, 8), 4)

[array([[92, 54],
        [88, 70],
        [40, 13],
        [ 5, 70]]),
 array([[74, 32],
        [55, 64],
        [57, 69],
        [61, 59]]),
 array([[79, 39],
        [36, 62],
        [76, 39],
        [83, 30]]),
 array([[91, 86],
        [18, 52],
        [ 1, 37],
        [34, 79]])]

In [28]:
a = np.array([[1,2],[3,4]])
b = np.array([[5],[6]])
np.concatenate((a, b), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [29]:
arr = np.random.randint(20, size=64).reshape(8, 8)
arr

array([[ 9, 14,  9,  0,  4,  1,  1, 17],
       [ 5,  0,  4,  0, 19,  2, 18,  0],
       [ 5,  9,  6, 13, 15,  8, 13, 17],
       [ 1, 16, 17, 13,  2, 10, 17,  4],
       [19,  2, 14,  1, 17,  4,  8,  5],
       [13,  4,  6,  0,  5,  2,  7, 12],
       [ 7,  3, 14, 10,  0,  8,  4, 10],
       [15, 10,  3, 16, 11, 17,  2,  7]])

In [30]:
np.hsplit(arr, [3, 5, 6, ])

[array([[ 9, 14,  9],
        [ 5,  0,  4],
        [ 5,  9,  6],
        [ 1, 16, 17],
        [19,  2, 14],
        [13,  4,  6],
        [ 7,  3, 14],
        [15, 10,  3]]),
 array([[ 0,  4],
        [ 0, 19],
        [13, 15],
        [13,  2],
        [ 1, 17],
        [ 0,  5],
        [10,  0],
        [16, 11]]),
 array([[ 1],
        [ 2],
        [ 8],
        [10],
        [ 4],
        [ 2],
        [ 8],
        [17]]),
 array([[ 1, 17],
        [18,  0],
        [13, 17],
        [17,  4],
        [ 8,  5],
        [ 7, 12],
        [ 4, 10],
        [ 2,  7]])]

In [31]:
np.split(arr, [3, 5, 6, ])

[array([[ 9, 14,  9,  0,  4,  1,  1, 17],
        [ 5,  0,  4,  0, 19,  2, 18,  0],
        [ 5,  9,  6, 13, 15,  8, 13, 17]]),
 array([[ 1, 16, 17, 13,  2, 10, 17,  4],
        [19,  2, 14,  1, 17,  4,  8,  5]]),
 array([[13,  4,  6,  0,  5,  2,  7, 12]]),
 array([[ 7,  3, 14, 10,  0,  8,  4, 10],
        [15, 10,  3, 16, 11, 17,  2,  7]])]

In [32]:
np.split(arr, [3, 5, 6])

[array([[ 9, 14,  9,  0,  4,  1,  1, 17],
        [ 5,  0,  4,  0, 19,  2, 18,  0],
        [ 5,  9,  6, 13, 15,  8, 13, 17]]),
 array([[ 1, 16, 17, 13,  2, 10, 17,  4],
        [19,  2, 14,  1, 17,  4,  8,  5]]),
 array([[13,  4,  6,  0,  5,  2,  7, 12]]),
 array([[ 7,  3, 14, 10,  0,  8,  4, 10],
        [15, 10,  3, 16, 11, 17,  2,  7]])]

In [33]:
img = np.random.randint(10, size=42).reshape(14, 3)
img

array([[0, 3, 1],
       [3, 2, 9],
       [8, 1, 0],
       [8, 5, 0],
       [8, 4, 2],
       [0, 8, 9],
       [3, 4, 4],
       [0, 6, 1],
       [9, 9, 8],
       [9, 8, 6],
       [2, 1, 2],
       [8, 7, 1],
       [1, 8, 3],
       [9, 2, 6]])

In [34]:
num_splits = 7

splits = np.vsplit(img, num_splits)
splits

[array([[0, 3, 1],
        [3, 2, 9]]),
 array([[8, 1, 0],
        [8, 5, 0]]),
 array([[8, 4, 2],
        [0, 8, 9]]),
 array([[3, 4, 4],
        [0, 6, 1]]),
 array([[9, 9, 8],
        [9, 8, 6]]),
 array([[2, 1, 2],
        [8, 7, 1]]),
 array([[1, 8, 3],
        [9, 2, 6]])]

In [35]:
last_band = splits[-1]
rest_of_bands = splits[:-1]

In [36]:
np.vstack(rest_of_bands)

array([[0, 3, 1],
       [3, 2, 9],
       [8, 1, 0],
       [8, 5, 0],
       [8, 4, 2],
       [0, 8, 9],
       [3, 4, 4],
       [0, 6, 1],
       [9, 9, 8],
       [9, 8, 6],
       [2, 1, 2],
       [8, 7, 1]])

In [37]:
np.vstack((splits[-1], np.vstack(splits[:-1])))

array([[1, 8, 3],
       [9, 2, 6],
       [0, 3, 1],
       [3, 2, 9],
       [8, 1, 0],
       [8, 5, 0],
       [8, 4, 2],
       [0, 8, 9],
       [3, 4, 4],
       [0, 6, 1],
       [9, 9, 8],
       [9, 8, 6],
       [2, 1, 2],
       [8, 7, 1]])

In [38]:
np.vstack([splits[-1]] + splits[:-1])

array([[1, 8, 3],
       [9, 2, 6],
       [0, 3, 1],
       [3, 2, 9],
       [8, 1, 0],
       [8, 5, 0],
       [8, 4, 2],
       [0, 8, 9],
       [3, 4, 4],
       [0, 6, 1],
       [9, 9, 8],
       [9, 8, 6],
       [2, 1, 2],
       [8, 7, 1]])