<a href="https://colab.research.google.com/github/thecont1/class-sharing/blob/main/Oct24_Numpy_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [ ]:
b = a.reshape(2, 2)
b

array([[0, 1],
       [2, 3]])

In [ ]:
np.shares_memory(a, b)

True

In [ ]:
a[0] = 100
a

array([100,   1,   2,   3])

In [ ]:
b

array([[100,   1],
       [  2,   3]])

In [ ]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [ ]:
c = a + 2
c

array([2, 3, 4, 5])

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
c

array([2, 3, 4, 5])

In [ ]:
a[0] = 50
a

array([50,  1,  2,  3])

In [ ]:
c

array([2, 3, 4, 5])

In [ ]:
np.shares_memory(a, c)  # Check if a & c have same memory

False

In [ ]:
print(2 + 3)

5


In [ ]:
a= np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [ ]:
np.shares_memory(a,b)
# Shallow copy

True

In [ ]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [ ]:
c = a[a % 1 == 0]
c

array([0, 1, 2, 3])

In [ ]:
a[0] = 20

In [ ]:
a

array([20,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [ ]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.shares_memory(a,c) # Deep Copy

False

In [ ]:
d = c

In [ ]:
np.shares_memory(d, c)

True

In [ ]:
a

array([20,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [ ]:
a_shallow_copy = a.view() # Function to create shallow copy
a_shallow_copy

array([20,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [ ]:
np.shares_memory(a, a_shallow_copy)

True

In [ ]:
a_deep_copy = a.copy()  # Function to create deep copy
a_deep_copy

array([20,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [ ]:
np.shares_memory(a, a_deep_copy)

False

In [ ]:
t = 10

In [ ]:
r = t.view()

AttributeError: 'int' object has no attribute 'view'

In [ ]:
a = np.array([0,1,2,3,4,5])
b = a[a%1 == 0]   # Deep Copy
b[0] = 10
a[:2]   # Slicing -> start to (end-1)

array([0, 1])

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
view_arr = arr.view()   # Shallow Copy -> Same memory -> Any change in one will be reflected in another.
view_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
view_arr[4] = 420
view_arr

array([  0,   1,   2,   3, 420,   5,   6,   7,   8,   9])

In [ ]:
arr

array([  0,   1,   2,   3, 420,   5,   6,   7,   8,   9])

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
copy_arr = arr.copy()   # Deep Copy -> New memory location for copy therefore change in one will not reflect in another.
copy_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
copy_arr[3] = 45
copy_arr

array([ 0,  1,  2, 45,  4,  5,  6,  7,  8,  9])

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
q = a

In [ ]:
np.shares_memory(a, q)

True

In [ ]:
arr = np.array([1, 'm', [1,2,3]], dtype = 'object')
arr

array([1, 'm', list([1, 2, 3])], dtype=object)

In [ ]:
copy_arr = arr.copy()   # Exception of .copy() i.e. creates shallow copy
copy_arr

array([1, 'm', list([1, 2, 3])], dtype=object)

In [ ]:
arr[2][0] = 15
arr

array([1, 'm', list([15, 2, 3])], dtype=object)

In [ ]:
copy_arr

array([1, 'm', list([15, 2, 3])], dtype=object)

In [ ]:
copy_arr[0] = 20
copy_arr

array([20, 'm', list([15, 2, 3])], dtype=object)

In [ ]:
arr

array([1, 'm', list([15, 2, 3])], dtype=object)

In [ ]:
import copy
copy_arr_2 = copy.deepcopy(arr)   # Deepcopy
copy_arr_2

array([1, 'm', list([15, 2, 3])], dtype=object)

In [ ]:
arr[0] = 50
arr

array([50, 'm', list([15, 2, 3])], dtype=object)

In [ ]:
copy_arr_2

array([1, 'm', list([15, 2, 3])], dtype=object)

In [ ]:
x = np.array([1, 'm', [1,2,3]], dtype = 'object')
x

array([1, 'm', list([1, 2, 3])], dtype=object)

In [ ]:
y = x.copy()    # Shallow Copy
y

array([1, 'm', list([1, 2, 3])], dtype=object)

In [ ]:
x[0] = 200
x

array([200, 'm', list([1, 2, 3])], dtype=object)

In [ ]:
y

array([1, 'm', list([1, 2, 3])], dtype=object)

In [ ]:
x[2][0] = 330
x

array([200, 'm', list([330, 2, 3])], dtype=object)

In [ ]:
y

array([1, 'm', list([330, 2, 3])], dtype=object)

In [ ]:
x = np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.split(x, 3)    # Diving into 3 equal part

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [ ]:
b = np.arange(10)
np.split(b, 3)

ValueError: array split does not result in an equal division

In [ ]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.split(b, 2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [ ]:
# np.split(arr, n)  -> Divides arr into 'n' equal part.

In [ ]:
c = np.arange(16)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
np.split(c, [3, 8, 10])

[array([0, 1, 2]),
 array([3, 4, 5, 6, 7]),
 array([8, 9]),
 array([10, 11, 12, 13, 14, 15])]

In [ ]:
# np.split(c, [n1, n2, n3]) -> Divides the arr from 0 to (n1-1), form n1 to (n2-1), from n2 to (n3-1) & from n3 to end.

In [ ]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.split(b, [3, 7, 5])    # Imp. to keep the list sorted to get the desigred result.

[array([0, 1, 2]),
 array([3, 4, 5, 6]),
 array([], dtype=int64),
 array([5, 6, 7, 8, 9])]

In [ ]:
x = np.arange(16).reshape(4, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.hsplit(x, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
np.vsplit(x, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [ ]:
np.vsplit(x, np.array([3]))

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [ ]:
a = np.arange(1, 5)
b = np.arange(2, 6)
c = np.arange(3, 7)

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
b

array([2, 3, 4, 5])

In [ ]:
c

array([3, 4, 5, 6])

In [ ]:
np.vstack([b, a, c])    # Important to keep the size of each array same for it to work.

array([[2, 3, 4, 5],
       [1, 2, 3, 4],
       [3, 4, 5, 6]])

In [ ]:
d = np.arange(3, 10)
d

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.vstack([b, a, d])

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 2 has size 7

In [ ]:
a = np.arange(5).reshape(5, 1)
a

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [ ]:
b = np.arange(15).reshape(5, 3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
np.hstack([a, b])

array([[ 0,  0,  1,  2],
       [ 1,  3,  4,  5],
       [ 2,  6,  7,  8],
       [ 3,  9, 10, 11],
       [ 4, 12, 13, 14]])

In [ ]:
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])

In [ ]:
a

array([[1],
       [2],
       [3]])

In [ ]:
b

array([[4],
       [5],
       [6]])

In [ ]:
np.vstack((a, b))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])
np.hstack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
b = np.array([[1,2,3], [4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.concatenate([a, b], axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [ ]:
c = np.array([[1,2,3]])
c

array([[1, 2, 3]])

In [ ]:
np.concatenate([c, b], axis=0)  # axis=0 -> vstack

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.concatenate([c, b], axis=1)  # axis=1 -> hstack

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 1 and the array at index 1 has size 2

In [ ]:
a = np.arange(6).reshape(3, 2)
b = np.arange(9).reshape(3, 3)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.concatenate([a, b], axis = 1) # axis=1 -> hstack

array([[0, 1, 0, 1, 2],
       [2, 3, 3, 4, 5],
       [4, 5, 6, 7, 8]])

In [ ]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6,7,8]])

np.concatenate([a, b], axis = None)

# axis=None joins and converts to 1D

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)   # axis=0 -> vstack

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1